"""
Expanded ASL phrases dictionary with 300+ entries
"""

asl_phrases = {
    # Basic greetings and responses
    "thumbs_up": "Yes / Good",
    "thumbs_down": "No / Bad",
    "open_palm": "Hello / Hi",
    "wave": "Goodbye / Bye",
    "ok_sign": "OK / I understand",
    "fist": "Stop",
    
    # Questions and common phrases
    "question_mark": "What? / Question",
    "pointing_index": "I / Me",
    "pointing_out": "You",
    "pointing_up": "One moment please",
    "pinch": "A little bit",
    "spread_fingers": "Five / Help",
    "victory": "Peace / Two",
    
    # Time-related
    "time_sign": "What time is it?",
    "clock_circle": "Time / Clock",
    "morning_sign": "Morning / AM",
    "evening_sign": "Evening / PM",
    "wait_sign": "Wait / Later",
    "now_sign": "Now / Right now",
    "today_sign": "Today",
    "tomorrow_sign": "Tomorrow",
    "yesterday_sign": "Yesterday",
    "week_sign": "Week",
    "month_sign": "Month",
    "year_sign": "Year",
    "hour_sign": "Hour",
    "minute_sign": "Minute",
    "second_sign": "Second",
    "day_sign": "Day",
    "night_sign": "Night",
    "soon_sign": "Soon",
    "late_sign": "Late",
    "early_sign": "Early",
    
    # Needs and feelings
    "eat_sign": "Eat / Food / Hungry",
    "drink_sign": "Drink / Thirsty",
    "sleep_sign": "Sleep / Tired",
    "bathroom_sign": "Bathroom / Restroom",
    "help_sign": "Help / Need assistance",
    "pain_sign": "Pain / Hurt",
    "happy_sign": "Happy / Glad",
    "sad_sign": "Sad / Unhappy",
    "angry_sign": "Angry / Mad",
    "scared_sign": "Scared / Afraid",
    "surprised_sign": "Surprised",
    "confused_sign": "Confused",
    "bored_sign": "Bored",
    "excited_sign": "Excited",
    "calm_sign": "Calm",
    "nervous_sign": "Nervous",
    "sick_sign": "Sick / Ill",
    "healthy_sign": "Healthy",
    "hot_sign": "Hot",
    "cold_sign": "Cold",
    "comfortable_sign": "Comfortable",
    "uncomfortable_sign": "Uncomfortable",
    
    # Locations and directions
    "home_sign": "Home",
    "work_sign": "Work / Job",
    "school_sign": "School / Education",
    "hospital_sign": "Hospital / Doctor",
    "store_sign": "Store / Shop",
    "left_sign": "Left",
    "right_sign": "Right",
    "up_sign": "Up / Above",
    "down_sign": "Down / Below",
    "forward_sign": "Forward",
    "backward_sign": "Backward",
    "here_sign": "Here",
    "there_sign": "There",
    "far_sign": "Far",
    "near_sign": "Near",
    "inside_sign": "Inside",
    "outside_sign": "Outside",
    "around_sign": "Around",
    "through_sign": "Through",
    "across_sign": "Across",
    "between_sign": "Between",
    
    # Communication
    "understand_sign": "Understand",
    "dont_understand_sign": "Don't understand",
    "slow_sign": "Slow down please",
    "repeat_sign": "Repeat please",
    "thank_you_sign": "Thank you",
    "sorry_sign": "Sorry / Excuse me",
    "name_sign": "Name / What's your name?",
    "sign_language_sign": "Sign language",
    "speak_sign": "Speak",
    "listen_sign": "Listen",
    "read_sign": "Read",
    "write_sign": "Write",
    "text_sign": "Text message",
    "call_sign": "Call / Phone",
    "email_sign": "Email",
    "chat_sign": "Chat",
    "meet_sign": "Meet",
    "introduce_sign": "Introduce",
    "explain_sign": "Explain",
    "tell_sign": "Tell",
    "ask_sign": "Ask",
    "answer_sign": "Answer",
    
    # Numbers
    "one_sign": "One",
    "two_sign": "Two",
    "three_sign": "Three",
    "four_sign": "Four",
    "five_sign": "Five",
    "six_sign": "Six",
    "seven_sign": "Seven",
    "eight_sign": "Eight",
    "nine_sign": "Nine",
    "ten_sign": "Ten",
    "zero_sign": "Zero",
    "hundred_sign": "Hundred",
    "thousand_sign": "Thousand",
    "million_sign": "Million",
    "first_sign": "First",
    "second_sign": "Second",
    "third_sign": "Third",
    "last_sign": "Last",
    "many_sign": "Many",
    "few_sign": "Few",
    
    # Emergency
    "emergency_sign": "Emergency",
    "call_911_sign": "Call 911",
    "fire_sign": "Fire",
    "police_sign": "Police",
    "ambulance_sign": "Ambulance / Medical help",
    "danger_sign": "Danger",
    "warning_sign": "Warning",
    "help_me_sign": "Help me",
    "accident_sign": "Accident",
    "lost_sign": "Lost",
    "found_sign": "Found",
    
    # Family
    "family_sign": "Family",
    "mother_sign": "Mother / Mom",
    "father_sign": "Father / Dad",
    "parent_sign": "Parent",
    "child_sign": "Child",
    "son_sign": "Son",
    "daughter_sign": "Daughter",
    "brother_sign": "Brother",
    "sister_sign": "Sister",
    "sibling_sign": "Sibling",
    "husband_sign": "Husband",
    "wife_sign": "Wife",
    "spouse_sign": "Spouse",
    "grandparent_sign": "Grandparent",
    "grandmother_sign": "Grandmother",
    "grandfather_sign": "Grandfather",
    "grandchild_sign": "Grandchild",
    "aunt_sign": "Aunt",
    "uncle_sign": "Uncle",
    "cousin_sign": "Cousin",
    "niece_sign": "Niece",
    "nephew_sign": "Nephew",
    "baby_sign": "Baby",
    
    # Food and drink
    "food_sign": "Food",
    "drink_water_sign": "Water",
    "coffee_sign": "Coffee",
    "tea_sign": "Tea",
    "juice_sign": "Juice",
    "milk_sign": "Milk",
    "soda_sign": "Soda / Pop",
    "alcohol_sign": "Alcohol",
    "breakfast_sign": "Breakfast",
    "lunch_sign": "Lunch",
    "dinner_sign": "Dinner",
    "snack_sign": "Snack",
    "fruit_sign": "Fruit",
    "vegetable_sign": "Vegetable",
    "meat_sign": "Meat",
    "chicken_sign": "Chicken",
    "fish_sign": "Fish",
    "bread_sign": "Bread",
    "cheese_sign": "Cheese",
    "egg_sign": "Egg",
    "rice_sign": "Rice",
    "pasta_sign": "Pasta",
    "pizza_sign": "Pizza",
    "hamburger_sign": "Hamburger",
    "sandwich_sign": "Sandwich",
    "salad_sign": "Salad",
    "soup_sign": "Soup",
    "dessert_sign": "Dessert",
    "ice_cream_sign": "Ice cream",
    "cake_sign": "Cake",
    "chocolate_sign": "Chocolate",
    "sugar_sign": "Sugar",
    "salt_sign": "Salt",
    "pepper_sign": "Pepper",
    
    # Clothing
    "clothes_sign": "Clothes / Clothing",
    "shirt_sign": "Shirt",
    "pants_sign": "Pants",
    "dress_sign": "Dress",
    "skirt_sign": "Skirt",
    "jacket_sign": "Jacket",
    "coat_sign": "Coat",
    "sweater_sign": "Sweater",
    "hat_sign": "Hat",
    "shoes_sign": "Shoes",
    "socks_sign": "Socks",
    "gloves_sign": "Gloves",
    "scarf_sign": "Scarf",
    "glasses_sign": "Glasses",
    "watch_sign": "Watch",
    "jewelry_sign": "Jewelry",
    "ring_sign": "Ring",
    "necklace_sign": "Necklace",
    "earrings_sign": "Earrings",
    
    # Colors
    "color_sign": "Color",
    "red_sign": "Red",
    "blue_sign": "Blue",
    "green_sign": "Green",
    "yellow_sign": "Yellow",
    "orange_sign": "Orange",
    "purple_sign": "Purple",
    "pink_sign": "Pink",
    "brown_sign": "Brown",
    "black_sign": "Black",
    "white_sign": "White",
    "gray_sign": "Gray",
    
    # Weather
    "weather_sign": "Weather",
    "sunny_sign": "Sunny",
    "cloudy_sign": "Cloudy",
    "rainy_sign": "Rainy",
    "snowy_sign": "Snowy",
    "windy_sign": "Windy",
    "storm_sign": "Storm",
    "hot_weather_sign": "Hot weather",
    "cold_weather_sign": "Cold weather",
    "temperature_sign": "Temperature",
    "forecast_sign": "Forecast",
    
    # Transportation
    "car_sign": "Car",
    "bus_sign": "Bus",
    "train_sign": "Train",
    "airplane_sign": "Airplane",
    "bicycle_sign": "Bicycle",
    "motorcycle_sign": "Motorcycle",
    "walk_sign": "Walk",
    "run_sign": "Run",
    "drive_sign": "Drive",
    "ride_sign": "Ride",
    "fly_sign": "Fly",
    "travel_sign": "Travel",
    "trip_sign": "Trip",
    "vacation_sign": "Vacation",
    
    # Places
    "city_sign": "City",
    "town_sign": "Town",
    "country_sign": "Country",
    "state_sign": "State",
    "building_sign": "Building",
    "house_sign": "House",
    "apartment_sign": "Apartment",
    "office_sign": "Office",
    "restaurant_sign": "Restaurant",
    "cafe_sign": "Cafe",
    "park_sign": "Park",
    "library_sign": "Library",
    "museum_sign": "Museum",
    "theater_sign": "Theater",
    "movie_sign": "Movie",
    "beach_sign": "Beach",
    "mountain_sign": "Mountain",
    "forest_sign": "Forest",
    "river_sign": "River",
    "lake_sign": "Lake",
    "ocean_sign": "Ocean",
    
    # Technology
    "computer_sign": "Computer",
    "laptop_sign": "Laptop",
    "tablet_sign": "Tablet",
    "phone_sign": "Phone",
    "smartphone_sign": "Smartphone",
    "internet_sign": "Internet",
    "website_sign": "Website",
    "app_sign": "App",
    "software_sign": "Software",
    "hardware_sign": "Hardware",
    "camera_sign": "Camera",
    "video_sign": "Video",
    "photo_sign": "Photo",
    "television_sign": "Television",
    "radio_sign": "Radio",
    "battery_sign": "Battery",
    "charge_sign": "Charge",
    
    # Education
    "learn_sign": "Learn",
    "teach_sign": "Teach",
    "student_sign": "Student",
    "teacher_sign": "Teacher",
    "class_sign": "Class",
    "course_sign": "Course",
    "lesson_sign": "Lesson",
    "homework_sign": "Homework",
    "test_sign": "Test",
    "exam_sign": "Exam",
    "grade_sign": "Grade",
    "pass_sign": "Pass",
    "fail_sign": "Fail",
    "graduate_sign": "Graduate",
    "degree_sign": "Degree",
    "certificate_sign": "Certificate",
    
    # Work
    "job_sign": "Job",
    "career_sign": "Career",
    "profession_sign": "Profession",
    "business_sign": "Business",
    "company_sign": "Company",
    "manager_sign": "Manager",
    "employee_sign": "Employee",
    "boss_sign": "Boss",
    "coworker_sign": "Coworker",
    "meeting_sign": "Meeting",
    "interview_sign": "Interview",
    "hire_sign": "Hire",
    "fire_sign": "Fire (from job)",
    "quit_sign": "Quit",
    "retire_sign": "Retire",
    "salary_sign": "Salary",
    "pay_sign": "Pay",
    "money_sign": "Money",
    "dollar_sign": "Dollar",
    "cent_sign": "Cent",
    "expensive_sign": "Expensive",
    "cheap_sign": "Cheap",
    "free_sign": "Free",
    "cost_sign": "Cost",
    "price_sign": "Price",
    "buy_sign": "Buy",
    "sell_sign": "Sell",
    "shop_sign": "Shop",
    "purchase_sign": "Purchase",
    "receipt_sign": "Receipt",
    "discount_sign": "Discount",
    "sale_sign": "Sale",
    
    # Health
    "doctor_sign": "Doctor",
    "nurse_sign": "Nurse",
    "patient_sign": "Patient",
    "medicine_sign": "Medicine",
    "pill_sign": "Pill",
    "prescription_sign": "Prescription",
    "appointment_sign": "Appointment",
    "checkup_sign": "Checkup",
    "vaccine_sign": "Vaccine",
    "injection_sign": "Injection",
    "surgery_sign": "Surgery",
    "therapy_sign": "Therapy",
    "recovery_sign": "Recovery",
    "allergy_sign": "Allergy",
    "headache_sign": "Headache",
    "stomachache_sign": "Stomachache",
    "fever_sign": "Fever",
    "cough_sign": "Cough",
    "cold_sick_sign": "Cold (illness)",
    "flu_sign": "Flu",
    "disease_sign": "Disease",
    "infection_sign": "Infection",
    "injury_sign": "Injury",
    "wound_sign": "Wound",
    "broken_sign": "Broken",
    "bandage_sign": "Bandage",
    "wheelchair_sign": "Wheelchair",
    "crutches_sign": "Crutches",
    
    # Activities
    "play_sign": "Play",
    "game_sign": "Game",
    "sport_sign": "Sport",
    "exercise_sign": "Exercise",
    "swim_sign": "Swim",
    "dance_sign": "Dance",
    "sing_sign": "Sing",
    "music_sign": "Music",
    "art_sign": "Art",
    "draw_sign": "Draw",
    "paint_sign": "Paint",
    "cook_sign": "Cook",
    "bake_sign": "Bake",
    "clean_sign": "Clean",
    "wash_sign": "Wash",
    "fix_sign": "Fix",
    "build_sign": "Build",
    "make_sign": "Make",
    "create_sign": "Create",
    "design_sign": "Design",
    "plan_sign": "Plan",
    "organize_sign": "Organize",
    "celebrate_sign": "Celebrate",
    "party_sign": "Party",
    "birthday_sign": "Birthday",
    "holiday_sign": "Holiday",
    "christmas_sign": "Christmas",
    "new_year_sign": "New Year",
    "thanksgiving_sign": "Thanksgiving",
    "halloween_sign": "Halloween",
    
    # Descriptive
    "big_sign": "Big",
    "small_sign": "Small",
    "tall_sign": "Tall",
    "short_sign": "Short",
    "long_sign": "Long",
    "wide_sign": "Wide",
    "narrow_sign": "Narrow",
    "thick_sign": "Thick",
    "thin_sign": "Thin",
    "heavy_sign": "Heavy",
    "light_sign": "Light (weight)",
    "fast_sign": "Fast",
    "slow_sign": "Slow",
    "hard_sign": "Hard",
    "soft_sign": "Soft",
    "strong_sign": "Strong",
    "weak_sign": "Weak",
    "old_sign": "Old",
    "new_sign": "New",
    "young_sign": "Young",
    "beautiful_sign": "Beautiful",
    "ugly_sign": "Ugly",
    "clean_adj_sign": "Clean (adjective)",
    "dirty_sign": "Dirty",
    "wet_sign": "Wet",
    "dry_sign": "Dry",
    "empty_sign": "Empty",
    "full_sign": "Full",
    "open_sign": "Open",
    "closed_sign": "Closed",
    "same_sign": "Same",
    "different_sign": "Different",
    "right_correct_sign": "Right (correct)",
    "wrong_sign": "Wrong",
    "true_sign": "True",
    "false_sign": "False",
    "possible_sign": "Possible",
    "impossible_sign": "Impossible",
    "easy_sign": "Easy",
    "difficult_sign": "Difficult",
    "important_sign": "Important",
    "serious_sign": "Serious",
    "funny_sign": "Funny",
    "interesting_sign": "Interesting",
    "boring_sign": "Boring",
}

# Phrase complexity mapping
phrase_complexity = {
    # Basic gestures (easier to detect)
    "thumbs_up": "basic",
    "thumbs_down": "basic",
    "open_palm": "basic",
    "wave": "basic",
    "fist": "basic",
    "pointing_index": "basic",
    "pointing_up": "basic",
    "victory": "basic",
    "spread_fingers": "basic",
    "ok_sign": "basic",
    "pinch": "basic",
    "one_sign": "basic",
    "two_sign": "basic",
    "three_sign": "basic",
    "four_sign": "basic",
    "five_sign": "basic",
}

# Set default complexity for all other phrases
for key in asl_phrases:
    if key not in phrase_complexity:
        if key.endswith("_sign"):
            phrase_complexity[key] = "advanced"
        else:
            phrase_complexity[key] = "intermediate"